require_relative '../../node_modules/react-native/scripts/react_native_pods'

platform :ios, '13.4'
install! 'cocoapods', :deterministic_uuids => false

# Firebase temporarily disabled; comment out global modular headers and dynamic frameworks
# use_modular_headers!
# use_frameworks! :linkage => :dynamic

# Force all pods to use dynamic frameworks
def use_frameworks_for_all_pods!
  use_frameworks! :linkage => :dynamic
end

target 'JuanLMS' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  
  # Stream Video iOS SDK
  pod 'StreamVideo', :path => '../../node_modules/@stream-io/video-react-native-sdk/ios'
  
  # Firebase temporarily disabled; remove explicit Google/Firebase pods
  
  # Let React Native auto-link handle Firebase pods

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'JuanLMSTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Remove Firebase/Google-specific overrides during temporary removal
      end
    end
  end
end
