import { StyleSheet } from 'react-native';

const StudentSupportStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f2f2f2',
    paddingTop: 40,
    alignItems: 'center',
  },
  header: {
    alignItems: 'flex-start', // Align logo to the left
    width: '100%',            // Ensure full width so alignItems works properly
    paddingLeft: 20,          // Optional padding from the left edge
    marginBottom: 10,
  },
  logo: {
    width: 120,
    height: 40,
    resizeMode: 'contain',
  },
  card: {
    backgroundColor: '#4B79A1',
    borderRadius: 20,
    padding: 20,
    width: '90%',
    marginTop: 10,
  },
  backButton: {
    alignSelf: 'flex-start',
  },
  backArrow: {
    fontSize: 24,
    color: 'white',
  },
  iconContainer: {
    alignItems: 'center',
    marginVertical: 20,
  },
  icon: {
    width: 80,
    height: 80,
    tintColor: 'white',
  },
  input: {
    backgroundColor: '#2A5D9F',
    borderRadius: 20,
    padding: 10,
    color: 'white',
    marginVertical: 8,
    textAlign: 'center',
  },
  textarea: {
    backgroundColor: '#144C8B',
    borderRadius: 20,
    padding: 10,
    color: 'white',
    height: 120,
    marginVertical: 8,
    textAlignVertical: 'top',
    textAlign: 'center',
  },
  buttonContainer: {
    flexDirection: 'row',
    marginTop: 20,
    justifyContent: 'space-between',
  },
  problemButton: {
    backgroundColor: '#FDF1C8',
    padding: 12,
    borderRadius: 20,
    flex: 1,
    marginRight: 10,
  },
  problemButtonText: {
    color: '#000',
    textAlign: 'center',
    fontWeight: '600',
  },
  requestButton: {
    backgroundColor: '#0E3162',
    padding: 12,
    borderRadius: 20,
    flex: 1,
  },
  requestButtonText: {
    color: 'white',
    textAlign: 'center',
    fontWeight: '600',
  },
  // Additions for new Support Center UI
  topBackground: {
    backgroundColor: '#00418b',
    height: 110,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    justifyContent: 'flex-end',
    paddingBottom: 15,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  backBtn: {
    position: 'absolute',
    left: 10,
    top: 40,
    zIndex: 10,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 40,
  },
  ticketCard: {
    backgroundColor: '#fff',
    borderRadius: 15,
    marginHorizontal: 16,
    marginTop: -40,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 2,
    borderColor: '#1976d2',
  },
  ticketTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 2,
  },
  ticketSubtitle: {
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
    marginBottom: 8,
  },
  ticketInput: {
    borderWidth: 2,
    borderColor: '#1976d2',
    borderRadius: 10,
    minHeight: 90,
    padding: 10,
    marginBottom: 8,
    color: '#222',
    backgroundColor: '#f5f5f5',
    textAlignVertical: 'top',
  },
  sendBtn: {
    alignSelf: 'flex-end',
    backgroundColor: '#e3eafc',
    borderRadius: 20,
    padding: 8,
    marginTop: 2,
  },
  commonTitle: {
    fontWeight: 'bold',
    fontSize: 18,
    textAlign: 'center',
    marginTop: 24,
    marginBottom: 8,
  },
  dropdownWrapper: {
    marginHorizontal: 16,
    marginBottom: 8,
  },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#1976d2',
    borderRadius: 8,
    padding: 10,
    justifyContent: 'space-between',
    backgroundColor: '#fff',
  },
  dropdownList: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#1976d2',
    borderRadius: 8,
    marginTop: 2,
    zIndex: 100,
  },
  dropdownItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  answerBox: {
    minHeight: 70,
    borderWidth: 2,
    borderColor: '#1976d2',
    borderRadius: 10,
    marginHorizontal: 16,
    backgroundColor: '#fff',
    padding: 10,
    marginBottom: 30,
  },
});

export default StudentSupportStyle;
